server:
    port: 20000
    compression:
      enabled: true
      mime-types: application/json,application/javascript,text/css,application/xml,text/html,text/xml,text/plain,stylesheet,script
zuul:
  routes:
    resource:
      path: /api/**
      sensitiveHeaders:
      url: http://localhost:9000
      rewrite: /api
    vk:
       path: /vk/**
       sensitiveHeaders:
       url: https://oauth.vk.com
       rewrite: /vk
    user:
      path: /uaa/**
      sensitiveHeaders:
      url: http://localhost:9999/uaa

spring:
    profiles:
        active: ${activeProfile}
