server:
    port: 20000
    compression:
      enabled: true
      mime-types: application/json,application/javascript,text/css,application/xml,text/html,text/xml,text/plain,stylesheet,script
zuul:
  ignoredPatterns: /app/**, /main**, /index.html, /firebase-messaging-sw.js
  routes:
    resource:
      path: /api/**
      sensitiveHeaders:
      url: http://localhost:9000
      rewrite: /api
    vk:
       path: /vk/**
       sensitiveHeaders:
       url: https://oauth.vk.com
       rewrite: /vk
    vk-api:
       path: /vk-api/**
       sensitiveHeaders:
       url: https://api.vk.com
       rewrite: /vk-api
    user:
      path: /uaa/**
      sensitiveHeaders:
      url: http://localhost:9999/uaa
    blog:
      path: /**
      sensitiveHeaders:
      url:  http://washing-time-blog.hostenko.com

spring:
    profiles:
        active: ${activeProfile}
