export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const SHOW_WAITING = 'SHOW_WAITING';
export const HIDE_WAITING = 'HIDE_WAITING';

export const LOAD_CLOTHES_TYPES_WITH_COUNT = 'LOAD_CLOTHES_TYPES_WITH_COUNT';
export const LOAD_CLEAN_CLOTHES = 'LOAD_CLEAN_CLOTHES';
export const LOAD_BASKET = 'LOAD_BASKET';

export const LOAD_SETTINGS = 'LOAD_SETTINGS';
export const SAVE_SETTINGS = 'SAVE_SETTINGS';
export const LOAD_FRIENDS = 'LOAD_FRIENDS';
export const SELECT_RECEIVER = 'SELECT_RECEIVER';
export const SELECT_SENDERS = 'SELECT_SENDERS';
